"""
knowledge/vector.py — ChromaDB Vector Store
Semantic search với sentence-transformers embedding.
"""
from pathlib import Path
import importlib.util
import shutil
from datetime import datetime
from typing import Dict, List, Optional, Tuple
from loguru import logger

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from config import (
    CHROMA_DIR, EMBED_MODEL, EMBED_CACHE,
    CHUNK_SIZE, CHUNK_OVERLAP,
    SIM_HIGH, SIM_LOW
)


class VectorStore:
    """ChromaDB + all-MiniLM-L6-v2 embedding."""

    COLLECTION = "knowledge"

    def __init__(self, persist_dir: Path = CHROMA_DIR):
        self.dir    = persist_dir
        self._coll  = None
        self._emb   = None
        self._ready = False

    def init(self) -> "VectorStore":
        try:
            import chromadb
            from chromadb.config import Settings

            # Chroma telemetry module path differs across versions.
            # Prefer NullTelemetry if available; otherwise keep telemetry disabled
            # and rely on compatible posthog package.
            settings_kwargs = {"anonymized_telemetry": False}
            null_telemetry = "chromadb.telemetry.product.null.NullTelemetry"
            if importlib.util.find_spec("chromadb.telemetry.product.null") is not None:
                settings_kwargs["chroma_product_telemetry_impl"] = null_telemetry

            settings = Settings(**settings_kwargs)
            self._coll = self._open_or_recover_collection(chromadb, settings)
        except ImportError as e:
            missing = getattr(e, "name", "") or ""
            if missing.startswith("chromadb.telemetry.product"):
                raise RuntimeError(
                    "Chroma telemetry module mismatch. "
                    "Use compatible deps: pip install 'chromadb==0.5.23' 'posthog<3'"
                ) from e
            raise RuntimeError("pip install chromadb")
        except TypeError as e:
            raise RuntimeError(
                "Chroma dependency mismatch on this Python version. "
                "Try: pip install 'chromadb==0.5.23' 'posthog<3'"
            ) from e

        try:
            from sentence_transformers import SentenceTransformer
            self._emb = SentenceTransformer(
                EMBED_MODEL, cache_folder=str(EMBED_CACHE)
            )
        except ImportError:
            raise RuntimeError("pip install sentence-transformers")

        self._ready = True
        logger.info(f"VectorStore ready: {self._coll.count()} docs")
        return self

    def _open_or_recover_collection(self, chromadb, settings):
        try:
            client = chromadb.PersistentClient(
                path=str(self.dir),
                settings=settings,
            )
            return client.get_or_create_collection(
                self.COLLECTION,
                metadata={"hnsw:space": "cosine"}
            )
        except KeyError as e:
            # Common on Jetson when reusing a Chroma directory generated by
            # different Chroma versions (missing _type in stored config).
            if str(e).strip("'\"") != "_type":
                raise

            backup = self._backup_incompatible_store()
            logger.warning(
                "Detected incompatible Chroma metadata (_type missing). "
                f"Backed up old store to: {backup}. Recreating clean Chroma store."
            )
            self.dir.mkdir(parents=True, exist_ok=True)
            client = chromadb.PersistentClient(
                path=str(self.dir),
                settings=settings,
            )
            return client.get_or_create_collection(
                self.COLLECTION,
                metadata={"hnsw:space": "cosine"}
            )

    def _backup_incompatible_store(self) -> Path:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup = self.dir.parent / f"{self.dir.name}_backup_{ts}"
        if self.dir.exists():
            shutil.move(str(self.dir), str(backup))
        return backup

    # ── Embedding ─────────────────────────────────────────────
    def _embed(self, texts: List[str]) -> List[List[float]]:
        return self._emb.encode(
            texts, normalize_embeddings=True, show_progress_bar=False
        ).tolist()

    # ── Indexing ──────────────────────────────────────────────
    def add_docs(self, docs: List[Dict]):
        """docs: [{id, text, concept_id, source, verified}]"""
        if not docs:
            return
        vecs  = self._embed([d["text"] for d in docs])
        ids   = [d["id"] for d in docs]
        metas = [{
            "concept_id": d.get("concept_id", ""),
            "source":     d.get("source", ""),
            "verified":   str(d.get("verified", True))
        } for d in docs]
        texts = [d["text"] for d in docs]
        self._coll.upsert(ids=ids, embeddings=vecs,
                          documents=texts, metadatas=metas)
        logger.info(f"Indexed {len(docs)} docs")

    def chunk_and_add(self, text: str, doc_id: str,
                      concept_id: str = "", source: str = "") -> int:
        words = text.split()
        chunks, i, idx = [], 0, 0
        while i < len(words):
            chunk_text = " ".join(words[i:i + CHUNK_SIZE])
            chunks.append({
                "id":         f"{doc_id}_c{idx}",
                "text":       chunk_text,
                "concept_id": concept_id,
                "source":     source,
                "verified":   True
            })
            i += CHUNK_SIZE - CHUNK_OVERLAP
            idx += 1
        self.add_docs(chunks)
        return len(chunks)

    # ── Search ────────────────────────────────────────────────
    def search(self, query: str, n=5,
               concept_id: str = None,
               verified_only: bool = True) -> List[Dict]:
        count = self._coll.count()
        if count == 0:
            return []

        where: Dict = {}
        if verified_only:
            where["verified"] = {"$eq": "True"}
        if concept_id:
            where["concept_id"] = {"$eq": concept_id}

        kw = dict(
            query_embeddings=[self._embed([query])[0]],
            n_results=min(n, count),
            include=["documents", "metadatas", "distances"]
        )
        if where:
            kw["where"] = where

        res = self._coll.query(**kw)

        out = []
        if res and res.get("documents"):
            for doc, meta, dist in zip(
                res["documents"][0],
                res["metadatas"][0],
                res["distances"][0]
            ):
                sim = 1.0 - dist / 2.0   # cosine dist [0,2] → sim [0,1]
                out.append({
                    "text":       doc,
                    "concept_id": meta.get("concept_id", ""),
                    "source":     meta.get("source", ""),
                    "score":      round(sim, 4)
                })
        out.sort(key=lambda x: x["score"], reverse=True)
        return out

    def search_graded(self, query: str, n=3,
                      concept_id: str = None) -> Tuple[List[Dict], str]:
        """
        Search + trả về confidence level cho anti-hallucination gate.
        Returns (results, "high"|"low"|"none")
        """
        results = self.search(query, n=n, concept_id=concept_id)
        if not results:
            return [], "none"
        top = results[0]["score"]
        if top >= SIM_HIGH:
            return results, "high"
        elif top >= SIM_LOW:
            return results, "low"
        return [], "none"

    def context_str(self, results: List[Dict], max_chars=600) -> str:
        parts, total = [], 0
        for r in results:
            t = r["text"].strip()
            if total + len(t) > max_chars:
                rem = max_chars - total
                if rem > 50:
                    parts.append(t[:rem] + "…")
                break
            parts.append(t)
            total += len(t)
        return "\n---\n".join(parts)

    def embed_single(self, text: str) -> List[float]:
        return self._embed([text])[0]

    @property
    def doc_count(self): return self._coll.count() if self._coll else 0
    @property
    def ready(self): return self._ready
