#!/usr/bin/env python3
"""Convert PNG/JPG images to C/C++ header RGB565 PROGMEM arrays."""

import argparse
import re
from pathlib import Path


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    return (r5 << 11) | (g6 << 5) | b5


def sanitize_symbol(name: str, prefix: str = "") -> str:
    symbol = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    symbol = re.sub(r"_+", "_", symbol).strip("_")
    if not symbol:
        symbol = "image"
    if symbol[0].isdigit():
        symbol = f"img_{symbol}"
    if prefix:
        symbol = f"{prefix}_{symbol}"
    return symbol


def collect_images(input_dir: Path, recursive: bool) -> list[Path]:
    patterns = ["*.png", "*.jpg", "*.jpeg", "*.bmp", "*.webp"]
    files: list[Path] = []
    for pattern in patterns:
        if recursive:
            files.extend(input_dir.rglob(pattern))
        else:
            files.extend(input_dir.glob(pattern))
    return sorted([p for p in files if p.is_file()])


def load_image_rgb(path: Path, bg_rgb: tuple[int, int, int]) -> tuple[list[tuple[int, int, int]], int, int]:
    try:
        from PIL import Image
    except ImportError as exc:
        raise RuntimeError("Pillow is required. Install with: pip install pillow") from exc

    img = Image.open(path)

    # Flatten transparency to background color for deterministic RGB565 output.
    if img.mode in ("RGBA", "LA") or (img.mode == "P" and "transparency" in img.info):
        rgba = img.convert("RGBA")
        bg = Image.new("RGBA", rgba.size, (*bg_rgb, 255))
        img = Image.alpha_composite(bg, rgba).convert("RGB")
    else:
        img = img.convert("RGB")

    w, h = img.size
    pixels = list(img.getdata())
    return pixels, w, h


def format_rgb565_array(values: list[int], items_per_line: int = 12) -> str:
    chunks = []
    for i in range(0, len(values), items_per_line):
        line_vals = ", ".join(f"0x{v:04x}" for v in values[i : i + items_per_line])
        chunks.append(f"  {line_vals},")
    return "\n".join(chunks)


def build_cpp_for_image(path: Path, symbol: str, bg_rgb: tuple[int, int, int]) -> str:
    pixels, w, h = load_image_rgb(path, bg_rgb)
    rgb565 = [rgb888_to_rgb565(r, g, b) for (r, g, b) in pixels]

    return (
        "// Auto-generated by convert_images_to_cpp.py\n"
        "// Format: RGB565 (16-bit), row-major, top-left to bottom-right\n"
        "#include <stdint.h>\n"
        "#ifndef PROGMEM\n"
        "#define PROGMEM\n"
        "#endif\n\n"
        f"// {path.name} | {w}x{h} | RGB565 (16-bit)\n"
        f"const uint16_t {symbol}_565[] PROGMEM = {{\n"
        f"{format_rgb565_array(rgb565)}\n"
        f"}};\n\n"
    )


def write_cpp_per_image(images: list[Path], output_dir: Path, var_prefix: str, bg_rgb: tuple[int, int, int]) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    written_files: list[Path] = []

    for path in images:
        symbol = sanitize_symbol(path.stem, var_prefix)
        cpp_code = build_cpp_for_image(path, symbol, bg_rgb)
        cpp_path = output_dir / f"{symbol}_rgb565.h"
        cpp_path.write_text(cpp_code, encoding="utf-8")
        written_files.append(cpp_path)

    return written_files


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert images to RGB565 arrays in .h files (PROGMEM)."
    )
    parser.add_argument(
        "--input_dir",
        type=str,
        default=None,
        help="Directory containing images (default: directory of this script)",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=None,
        help="Output directory for generated .h files (default: <script_dir>/cpp)",
    )
    parser.add_argument(
        "--recursive",
        action="store_true",
        help="Recursively find images in subfolders",
    )
    parser.add_argument(
        "--prefix",
        type=str,
        default="",
        help="Optional prefix added to generated C++ symbols",
    )
    parser.add_argument(
        "--bg",
        type=str,
        default="172,224,179",
        help="Background color for transparent pixels, format: R,G,B",
    )
    return parser.parse_args()


def parse_bg(bg: str) -> tuple[int, int, int]:
    parts = [p.strip() for p in bg.split(",")]
    if len(parts) != 3:
        raise ValueError("--bg must be in format R,G,B (e.g. 172,224,179)")
    vals = tuple(int(p) for p in parts)
    if any(v < 0 or v > 255 for v in vals):
        raise ValueError("Background values must be between 0 and 255")
    return vals


def main() -> None:
    args = parse_args()
    script_dir = Path(__file__).resolve().parent
    input_dir = Path(args.input_dir) if args.input_dir else script_dir
    output_dir = Path(args.output_dir) if args.output_dir else (script_dir / "cpp")

    if not input_dir.exists():
        raise FileNotFoundError(f"Input directory not found: {input_dir}")

    bg_rgb = parse_bg(args.bg)
    images = collect_images(input_dir, args.recursive)
    if not images:
        raise RuntimeError(f"No images found in: {input_dir}")

    written_files = write_cpp_per_image(images, output_dir, args.prefix, bg_rgb)

    print(f"Converted {len(images)} image(s)")
    print(f"Output directory: {output_dir.resolve()}")
    print("Generated files:")
    for cpp_file in written_files:
        print(f"- {cpp_file.name}")


if __name__ == "__main__":
    main()
